production:
  secret_key_base: 33cc8f5c744ea7ebeaef2fd0f2e8076eceb68ff61864dc76bc7a2d50437c87c49884ac47fe4dc97416e9e9d7dd19a4424ceed85f9f1b5beefa39ef5a24c4536c
development:
  secret_key_base: <%= ENV['secret_key_base'] %>
test:
  secret_key_base: <%= ENV['secret_key_base'] %>
